export default [
    { content: "# Hello, World", depth: 0, },
    { content: "This is ilse Langnar's Notebook", depth: 0, },
    { content: "You can use Markdown with those notes", depth: 0, },
    { content: "Some things you can use ->  ==Highlight== **Bold** *Italic* ~~Strike~~ ", depth: 0, },
    { content: "> He who has a why can bear almost any how - Friedrich Nietzsche", depth: 0, },
    { content: "[[Ilse]] do a **shift-click** or a **ctrl-click** on the link to open the file / graph", depth: 0, },
    { content: "## Shortcuts ", depth: 0, },
    { content: "alt+n New note", depth: 1, },
    { content: "alt+f Search", depth: 1, },
    { content: "alt+h Help", depth: 1, },
    { content: "alt+m Toggle Menu", depth: 1, },
    { content: "alt+c Configuration", depth: 1, },
    { content: "alt+d Toggle Daily Notes", depth: 1, },
    { content: "alt+o Open File", depth: 1, },
    { content: "## Indenting notes ", depth: 0, },
    { content: "*tab* Indent note ", depth: 1, },
    { content: "*shift-tab*: Unindent note", depth: 1, },
    { content: "## Link Click ", depth: 0, },
    { content: "*shift-click*: Open File", depth: 1, },
    { content: "*ctrl-click*: Open File Graph", depth: 1, },
]
